apiVersion: v1
kind: Config
clusters:
  - name: main-cluster
    cluster:
      server: http://localhost:8088
#      certificate-authority-data: <base64-encoded-ca-cert>
contexts:
  - name: main-context
    context:
      cluster: main-cluster
      user: main-user
current-context: my-context
preferences: {}
users:
  - name: main-user
#    user:
#      client-certificate-data: <base64-encoded-client-cert>
#      client-key-data: <base64-encoded-client-key>