apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  DEMO_DATASOURCE_URL: "jdbc:postgresql://ecommercedb.default.svc.cluster.local:5432/ecommerce"
  EDITOR_DATASOURCE_URL: "jdbc:postgresql://ecommercedb.default.svc.cluster.local:5432/editor"