apiVersion: v1
kind: ServiceAccount
metadata:
  name: engine-watcher
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: engine-watcher-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: engine-watcher-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: engine-watcher
    namespace: default
roleRef:
  kind: Role
  name: engine-watcher-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ecommerce
  labels:
    app: ecommerce
spec:
  replicas: 1
  serviceName: demo-service
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      name: ecommerce
      labels:
        app: ecommerce
    spec:
      serviceAccountName: engine-watcher
      containers:
        - name: demo
          image: host.minikube.internal:5000/ecommerce_builder-demo:latest
          volumeMounts:
            - mountPath: "$HOME/.kube/config"
              name: kubeconfig
          env:
            - name: DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATASOURCE_URL
                  name: config
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: database-credentials
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: database-credentials
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
            - protocol: TCP
              containerPort: 5005
      restartPolicy: Always
      volumes:
        - name: kubeconfig
          hostPath:
            path: /mnt/kube/cluster-config.yaml
            type: File
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: ecommerce
    statefulset.kubernetes.io/pod-name: ecommerce-0
  type: NodePort
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
      name: debug
      nodePort: 30005
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: external
      nodePort: 30080
