apiVersion: apps/v1
kind: Deployment
metadata:
  name: editor
  labels:
    app: editor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: editor
  template:
    metadata:
      name: editor
      labels:
        app: editor
    spec:
      containers:
        - name: editor
          image: host.minikube.internal:5000/ecommerce_builder-editor:latest
          env:
            - name: DEMO_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: DEMO_DATASOURCE_URL
                  name: config
            - name: DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: EDITOR_DATASOURCE_URL
                  name: config
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: database-credentials
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: database-credentials
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 5005
              protocol: TCP
          startupProbe:
            httpGet:
              port: 8080
              path: /health/startup
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: editor-service
spec:
    selector:
        app: editor
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
        nodePort: 30081
        name: external
      - protocol: TCP
        port: 5005
        targetPort: 5005
        nodePort: 30006
        name: debug
    type: NodePort