spring.application.name=ecommerce
spring.config.import=optional:configserver:
spring.jpa.database=postgresql
app.url=http://localhost:8080/
server.servlet.context-path=/ecommerce
spring.datasource.url=dbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=tipil
spring.datasource.password=12345
spring.mvc.static-path-pattern=/static/**
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.jdbc-url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.hikari.username=tipil
spring.datasource.hikari.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration