spring.application.name=ecommerce-demo
server.servlet.context-path=/
spring.mvc.static-path-pattern=/static/**
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=create
spring.datasource.editor.url=${EDITOR_DATASOURCE_URL:jdbc:postgresql://localhost:5432/editor}
spring.datasource.editor.username=${DATASOURCE_USERNAME:tipil}
spring.datasource.editor.password=${DATASOURCE_PASSWORD:12345}
spring.datasource.editor.driver-class-name=org.postgresql.Driver
spring.datasource.demo.url=${DEMO_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecommerce}
spring.datasource.demo.username=${DATASOURCE_USERNAME:tipil}
spring.datasource.demo.password=${DATASOURCE_PASSWORD:12345}
spring.datasource.demo.driver-class-name=org.postgresql.Driver
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.packages-to-scan=me.yusuf.ecommerce.controller,me.yusuf.ecommerce.engine
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
