spring.application.name=ecommerce
spring.jpa.database=postgresql
server.servlet.context-path=/
spring.mvc.static-path-pattern=/static/**
spring.jpa.generate-ddl=true
demo.plugins.partition-count=1
demo.plugins.replica-idx=1
spring.jpa.hibernate.ddl-auto=create
spring.datasource.hikari.jdbc-url=${DATASOURCE_URL:jdbc:postgresql://localhost:5432}/ecommerce
spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5432}/ecommerce
spring.datasource.hikari.schema=public
spring.datasource.hikari.username=${DATASOURCE_USERNAME:tipil}
spring.datasource.username=${DATASOURCE_USERNAME:tipil}
spring.datasource.hikari.password=${DATASOURCE_PASSWORD:12345}
spring.datasource.password=${DATASOURCE_PASSWORD:12345}
spring.datasource.driver-class-name=org.postgresql.Driver
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.packages-to-scan=me.yusuf.ecommerce.controller,me.yusuf.ecommerce.engine
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
