spring.application.name=ecommerce-editor
server.port=${SERVER_PORT:8080}
spring.jpa.database=postgresql
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5432/editor}
spring.datasource.username=${DATASOURCE_USERNAME:tipil}
spring.datasource.password=${DATASOURCE_PASSWORD:12345}
spring.datasource.demo.url=${DEMO_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecommerce}
spring.data.jdbc.dialect=postgresql
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/
spring.mvc.static-path-pattern=/static/**
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.packages-to-scan=me.yusuf.ecommerce_builder.editor.network
spring.mvc.pathmatch.matching-strategy=ant_path_matcher